apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-consumer-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-consumer-kafka
  template:
    metadata:
      labels:
        app: post-consumer-kafka
    spec:
      containers:
      - name: post-consumer-kafka
        image: post-consumer:v1
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: kafka-ui-config

        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
          
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcp-key-secret